reload_message: "&a&lButter&f&lMc &fè stato &f&lReloaded"


heal-amount: 20

messages:
  no-permission: "&cYou cannot do that!"


blocks:
  DIRT:
    - SAND
    - DIRT
    - GRASS_BLOCK
  SAND:
    - SAND
    - DIRT
codici:
  premio1:
    ricompensa:
      - "eco give %player% 100"